### ISSUE TITLE
Error while Running Example

### ISSUE THREAD

**Issue by Hrushi20** [second-state/opencvmini#4]
I've run the below command to build the wasmedge and corresponding plugins (Mac M1 Chip)- 

```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_PLUGINS=ON \
  -DWASMEDGE_PLUGIN_OPENCVMINI=ON \
  -DWASMEDGE_PLUGIN_TENSORFLOWLITE=ON \
  -DWASMEDGE_PLUGIN_IMAGE=ON \
  -GNinja ..
ninja
ninja install # might need `sudo`
```
Wasmedge was built successfully and all the *.dylib for the plugin were created in `/usr/local/lib/wasmedge` folder. I have the  *.dylib files in `~/.wasmedge/plugins/` folder as well.

<img width="989" alt="Screenshot 2023-08-02 at 9 16 25 PM" src="https://github.com/second-state/opencvmini/assets/65367566/fd38f53c-a7e6-4fd8-8c73-4bf170a11958">

I've set the OUT_DIR to $(pwd)/src as well to create the `generate.rs` file. 
However, while building the example project and running it on Wasmedge, I'm getting the following error

<img width="1029" alt="Screenshot 2023-08-02 at 9 18 26 PM" src="https://github.com/second-state/opencvmini/assets/65367566/98366c12-ab2f-4e12-b318-339fcaee64fd">

The plugin is being recognised but I'm not able to find the module to run the function. 
Below is the generated.rs file-

<img width="1029" alt="Screenshot 2023-08-03 at 2 33 52 AM" src="https://github.com/second-state/opencvmini/assets/65367566/14b7f9de-f6ba-471b-8174-75c421514c41">

**Comment by Hrushi20** [comment]
@hydai, I've tried all possible ways. I'm not sure where I am going wrong while running Opencvmini.

However, when I'm trying [wasi-logging](https://github.com/WasmEdge/WasmEdge/tree/master/examples/plugin/wasi-logging), I am able to run and view the logs. 

Thank You

**Comment by hydai** [comment]
Hi @Hrushi20 
Please checkout to the previous commits: a3272b9f1008c80ec33b4e5582cc5de7f0f27442
We introduced some new functions 3 days ago. And the related PR is not yet merged in the upstream. https://github.com/WasmEdge/WasmEdge/pull/2705

**Comment by Hrushi20** [comment]
Thanks. It worked.
